### PR TITLE
Added colorwheel and setting

### PR DESCRIPTION
**Pull request by jinhofer**
We have been using your plugin and very much liked it, but our user base would like to be able to add a custom color via hex through your plugin instead of going into the HTML to do so. With that in mind, I have created an extra button using a moodle core image that brings up a dialogue to add a custom color via hex. I have also included a setting to control whether or not this option is turned on.

### CODE REVIEW

**Comment by ndunand** [comment]
Hi,
Thanks for the feedback, and thanks for sharing. I'd be willing to merge this, but for the following issues:
 - there is no error management (e.g. I tried to type in "fcc" several times with no result or feedback;
 - if we're going to allow any color, would it not be nicer to provide a color picker?

**Comment by jinhofer** [comment]
The reason I didn't use a color picker is because I wasn't entirely sure how to do so. Since doing so would fix both of your noted issues, I'll start working on figuring it out!

**Comment by ndunand** [comment]
Yeah same problem for me, or I would have done it long ago. If you could look into it that would be great, I'd be happy to include it!

**Comment by jinhofer** [comment]
It wasn't easy, but I was able to do it! Feel free to test it out and include it if you like it.

**Comment by ndunand** [comment]
Thanks! I'll have a good look at it.

**Comment by ndunand** [comment]
Upon testing, this looks great! Quite easy to use, too. Thanks for sharing :+1: 

Now I just have to do a quick code review (to make sure I understand how things are working).

One question though: when clicking and dragging on the color wheel, it looks like one can't drag the selector past the zero-degree mark. Is that intended behavior?

**Comment by jinhofer** [comment]
To be honest, I took the template for the color wheel from YUI:
http://yuilibrary.com/yui/docs/color/hsl-picker.html
Which has it so that the selector can't go below 0 or above 360. I considered trying to remedy that, but since you can also click on the color you want, I decided that the risk of breaking everything wasn't really worth it.

**Comment by ndunand** [comment]
Thanks for the clarification.

**Comment by jinhofer** [comment]
Quick question, when do you intend to release the version with the custom color wheel to Moodle?

**Comment by ndunand** [comment]
Sure: last Wednesday 😊

**Comment by jinhofer** [comment]
Oh boy, do I feel foolish. Sorry about that!

**Comment by ndunand** [comment]
No worries, I wish every request was so easy to answer.

**Pull request merged**
